export const RECEIVE_MOVIES = 'RECEIVE_MOVIES'
export const RECEIVE_MOVIES_SETS = 'RECEIVE_MOVIES_SETS'
export const RECEIVE_SHOWS = 'RECEIVE_SHOWS'
export const RECEIVE_EPISODES = 'RECEIVE_EPISODES'
