export const RECEIVE_MOVIES = 'RECEIVE_MOVIES'
export const RECEIVE_MOVIES_SETS = 'RECEIVE_MOVIES_SETS'
export const RECEIVE_SHOWS = 'RECEIVE_SHOWS'
export const RECEIVE_EPISODES = 'RECEIVE_EPISODES'

export const RECIEVE_LIBRARIES_MOVIES = 'RECIEVE_LIBRARIES_MOVIES'
export const RECIEVE_LIBRARIES_SHOWS = 'RECIEVE_LIBRARIES_SHOWS'

export const UPDATE_SEEDBOX_IMPORT = 'UPDATE_SEEDBOX_IMPORT'
export const REMOVE_SEEDBOX_IMPORT = 'REMOVE_SEEDBOX_IMPORT'
